name: Build only

on: 
  push: 
    paths: 
      - 'Dockerfile'

jobs: 
  build-only: 
    runs-on: ubuntu-latest
    
    steps: 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: docker/build-push-action@v6
        with: 
          context: .
          push: false
          platforms: linux/amd64,linux/arm64
          tags: firebase-tools:${{ github.ref_name }}
